apiVersion: apps/v1beta1@
kind: Deployment
metadata:
  name: hkedevopstrain
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: hkedevopstrain
    spec:
      containers:
      - name: hkedevopstrain
        image: docker.io/pleungdev/andrewdevops:$BUILD_ID
        ports:
        - containerPort: 6555
---
apiVersion: v1
kind: Service
metadata:
  name: andrewdevops
spec:
  type: LoadBalancer
  ports:
  - port: 6555
  selector:
    app: andrewdevops
